import { Button } from "@heroui/button";
import { Card, CardBody, CardHeader } from "@heroui/card";
import { Chip } from "@heroui/chip";
import Link from "next/link";

const reports = [
  { name: "Term Performance Report", generatedBy: "Academic Office", date: "Mar 20, 2026", status: "Ready" },
  { name: "Attendance Summary", generatedBy: "Operations Desk", date: "Mar 19, 2026", status: "Ready" },
  { name: "Finance Collection Analysis", generatedBy: "Bursary", date: "Mar 18, 2026", status: "Pending" },
  { name: "Staff Productivity Snapshot", generatedBy: "HR Unit", date: "Mar 17, 2026", status: "Ready" },
];

export default function ReportPage() {
  return (
    <section className="space-y-5 py-4">
      <Card className="border border-emerald-100/70 bg-white/90 dark:border-emerald-300/20">
        <CardHeader className="flex flex-wrap items-end justify-between gap-3 px-6 pt-6">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-foreground/50">Analytics Desk</p>
            <h2 className="text-2xl font-semibold">Report Center</h2>
          </div>
          <Button as={Link} href="/school/report/generate" className="bg-emerald-600 text-white" radius="full">
            Generate New Report
          </Button>
        </CardHeader>
        <CardBody className="grid gap-3 px-6 pb-6">
          {reports.map((item) => (
            <div key={item.name} className="rounded-2xl border border-emerald-100/70 bg-white p-4 dark:border-emerald-300/20 dark:bg-slate-900/40">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <p className="text-sm font-semibold">{item.name}</p>
                <Chip className="border-0" color={item.status === "Ready" ? "primary" : "default"} size="sm" variant="flat">
                  {item.status}
                </Chip>
              </div>
              <p className="mt-1 text-sm text-foreground/70">Generated by: {item.generatedBy}</p>
              <p className="mt-1 text-xs text-foreground/60">Date: {item.date}</p>
            </div>
          ))}
        </CardBody>
      </Card>
    </section>
  );
}
